# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build and publish npm

on:
  release:
    types: [created]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run test

  publish-npm:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - run: npm version from-git --no-git-tag-version # update version in package.json before publishing it, but does not commit the change
      - run: npm install # to update package-lock.json
      - run: npm run build # generates dist folder
      - run: npm publish # publish to npm registry
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
